### ISSUE TITLE
Release binary?

### ISSUE THREAD

**Issue by sNakiex** [pitoniak32/fitff#1]
Is it possible to release a binary for the people who don't want to install the whole rust SDK on their machine?

**Comment by pitoniak32** [comment]
Hey, yeah I can do this adding some release workflows now.

**Comment by pitoniak32** [comment]
I guess my workflows don't release valid binaries, I need to look into the MUSL builds so this might not be done as quickly as I was planning

**Comment by pitoniak32** [comment]
Hey @sNakiex, the binary release should be up now for v0.1.2
https://github.com/pitoniak32/fitff/releases/tag/v0.1.2

**Comment by pitoniak32** [comment]
Hey @sNakiex, the binary release should be up now for v0.1.2
https://github.com/pitoniak32/fitff/releases/tag/v0.1.2
